[project]
name = "cldk-docs"
version = "0.5.0-dev"
description = "The official documentation page for Codellm-Devkit."
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = "==3.12.12"
authors = [
  { name = "Rahul Krishna", email = "i.m.ralk@gmail.com" },
  { name = "Rangeet Pan", email = "rangeet.pan@ibm.com" },
  { name = "Saurabh Sinhas", email = "sinhas@us.ibm.com" },
  { name = "Raju Pavuluri", email = "pavuluri@us.ibm.com" },
]
keywords = ["ibm", "llm", "large language models", "code analyzer", "syntax tree"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
]

dependencies = [
    "mkdocs-material[imaging]>=9.6.4,<10.0.0",
    "mkdocs-autorefs>=1.3.1,<2.0.0",
    "mkdocs-get-deps>=0.2.0,<0.3.0",
    "mkdocs-material-extensions>=1.3.1,<2.0.0",
    "mkdocstrings>=0.28.0,<0.29.0",
    "mkdocstrings-python>=1.15.0,<2.0.0",
    "mkdocs-git-revision-date-localized-plugin>=1.3.0,<2.0.0",
    "cldk>=1.0.6,<2.0.0",
  ]

[project.urls]
Homepage = "https://codellm-devkit.info"
Repository = "https://github.com/codellm-devkit/"

########################################
# Tool configurations (unchanged)
########################################
[tool.flake8]
max-line-length = 180
count = true

[tool.black]
line-length = 180

[tool.pylint.'MESSAGES CONTROL']
disable = "no-member,protected-access,global-statement"

[tool.pylint.FORMAT]
max-line-length = 180

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--pspec --cov=cldk --cov-fail-under=50"
testpaths = ["tests"]

[tool.coverage.run]
source = ["cldk"]
omit = [
  "venv/*",
  ".venv/*"
]

[tool.coverage.report]
show_missing = true
exclude_lines = [
  "pragma: no cover",
  "pragma: no branch",
  "pass",
  "subprocess.CalledProcessError",
  "sys.exit",
  "if __name__ == .__main__.:"
]
ignore_errors = true

[tool.coverage.xml]
output = "./coverage.xml"

[tool.coverage.html]
title = "Test Coverage Report"
directory = "coverage_html_report"

[tool.cldk.testing]
sample-application = "tests/resources/java/application/"
sample-application-analysis-json = "tests/resources/java/analysis_json/"
codeanalyzer-jar-path = "tests/resources/java/codeanalyzer_jars/"
