name: mkdocs-deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: pip install poetry
      - name: Clone python-sdk
        run: git clone --depth 1 https://github.com/codellm-devkit/python-sdk.git ../python-sdk
      - name: Install Dependencies
        run: poetry install --no-root
      - name: Install python-sdk into Poetry venv
        run: poetry run pip install -e ../python-sdk
      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force --verbose
